import type { EstateState } from "@/types/estate";

export const mockEstate: EstateState = {
  id: "demo-milligan",
  deceasedName: "Robert A. Milligan",
  dateOfDeath: "2026-06-03",
  appointmentDate: "2026-06-10",
  state: "california",
  executor: { name: "Dana Milligan", email: "dana@demo.com" },
  assets: [
    {
      id: "asset-real-estate-berkeley",
      type: "real_estate",
      description: "1847 Marin Ave, Berkeley CA",
      estimatedValue: 220000,
      appraised: false,
    },
    {
      id: "asset-wells-fargo-4412",
      type: "bank_account",
      description: "Wells Fargo checking ...4412",
      estimatedValue: 38240,
      appraised: true,
    },
  ],
  debts: [
    {
      id: "debt-ucsf",
      creditor: "UCSF Medical Center",
      amount: 4200,
      type: "unsecured",
      notified: false,
    },
  ],
  beneficiaries: [
    { id: "beneficiary-dana", name: "Dana Milligan", share: "40%" },
    { id: "beneficiary-sarah", name: "Sarah Milligan", share: "40%" },
    { id: "beneficiary-marcus", name: "Marcus Milligan", share: "20%" },
  ],
  documents: [],
  tasks: [
    {
      id: "task-notify-creditors",
      title: "Notify all known creditors by certified mail",
      status: "todo",
      phase: 2,
    },
    {
      id: "task-inventory-appraisal",
      title: "Prepare DE-160 Inventory and Appraisal",
      status: "todo",
      phase: 2,
    },
  ],
  alerts: [
    {
      id: "alert-de-160-inventory",
      severity: "critical",
      type: "deadline",
      title: "DE-160 Inventory & Appraisal is blocked",
      body: "The estate has assets that still need appraisal before the inventory can be filed.",
      rule: "DE-160 Inventory & Appraisal",
      daysRemaining: 9,
      timingStatus: "dated",
      actionRequired: "Schedule appraisals and prepare the DE-160 packet.",
      whatYouNeed: [],
      steps: [],
      createdAt: "2026-06-20T00:00:00Z",
      dismissed: false,
    },
    {
      id: "alert-creditor-notice",
      severity: "critical",
      type: "liability",
      title: "Known creditors have not been notified",
      body: "Known creditors must receive certified notice before distributions are made.",
      rule: "CA Probate Code §9051",
      daysRemaining: 20,
      timingStatus: "dated",
      actionRequired: "Send certified creditor notices to each known creditor.",
      whatYouNeed: [],
      steps: [],
      createdAt: "2026-06-20T00:00:00Z",
      dismissed: false,
    },
  ],
  letters: [],
  phase: 2,
  createdAt: "2026-06-20T00:00:00Z",
  updatedAt: "2026-06-20T00:00:00Z",
};
